micronaut:
  application:
    name: testMicronautData
datasources:
  default:
    driverClassName: oracle.jdbc.OracleDriver
    db-type: oracle
    #schema-generate: CREATE_DROP
    #dialect: ORACLE
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: desarrollo
    password: D3s4rr0ll0
netty:
  default:
    allocator:
      max-order: 3
